subs(chat,felin).
subs(lion,felin).
subs(chien,canide).
subs(canide,chien).
subs(souris,mammifere).
subs(felin,mammifere).
subs(canide,mammifere).
subs(mammifere,animal).
subs(canari,animal).
subs(animal,etreVivant).
subs(and(animal,plante),nothing).
subs(and(animal,some(aMaitre)),pet).
subs(pet,some(aMaitre)).
subs(some(aMaitre),all(aMaitre,humain)).
subs(chihuahua,and(chien,pet)).
subs(lion,carnivoreExc).
subs(carnivoreExc,predateur).
subs(animal,some(mange)).
subs(and(all(mange,nothing),some(mange)),nothing).

equiv(carnivoreExc,all(mange,animal)).
equiv(herbivoreExc,all(mange,plante)).

inst(felix,chat).
inst(pierre,humain).
instR(felix,pierre,aMaitre).
inst(princesse,chihuahua).
inst(marie,humain).
instR(princesse,marie,aMaitre).
inst(jerry,souris).
inst(titi,canari).
instR(felix,jerry,mange).
instR(felix,titi,mange).
